version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/modules/keypair"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/modules/network"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/modules/secgroup"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/modules/node"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

